spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:file:./backend/data/devdb;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # 개발: create/update, 운영: validate/none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
logging:
  level:
    com.realworld.backend.common: DEBUG
    com.realworld.backend.user: DEBUG
    com.realworld.backend.article: DEBUG
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace # 바인딩 파라미터 출력
    #org.springframework.boot.autoconfigure: DEBUG

jwt:
  secret: thisisasecretkeyforjwttoken-must-be-32bytes-long
  expiration: 3600000 # 1시간 (밀리초)
